# -*- coding: utf-8 -*-
"""TimeSeries_1_20251110.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBZXJLq8idFPVi-lwhzuQIkRZdjEJN2R

# [Time Series Forecasting in Python](https://learning.oreilly.com/library/view/time-series-forecasting/9781617299889/)

[中譯本](https://www.tenlong.com.tw/products/9787111754466?list_name=srh)


https://github.com/marcopeix/TimeSeriesForecastingInPython

# CH1

第1章瞭解時間序列預測

https://github.com/marcopeix/TimeSeriesForecastingInPython/tree/master
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from statsmodels.tsa.seasonal import seasonal_decompose, STL
df = pd.read_csv('https://raw.githubusercontent.com/marcopeix/AppliedTimeSeriesAnalysisWithPython/main/data/jj.csv')
df.head()

df['year'] = pd.DatetimeIndex(df['date']).year
df

fig, ax = plt.subplots()

ax.plot(df.date, df.data)
ax.set_xlabel('Date')
ax.set_ylabel('Earnings per share (USD)')

plt.xticks(np.arange(0, 85, 8), [1960, 1962, 1964, 1966, 1968, 1970, 1972, 1974, 1976, 1978, 1980])

fig.autofmt_xdate()
plt.tight_layout()

plt.savefig('figures/CH01_F01_peixeiro.png', dpi=300)

import os

fig, ax = plt.subplots()

ax.plot(df.date, df.data)
ax.set_xlabel('Date')
ax.set_ylabel('Earnings per share (USD)')

plt.xticks(np.arange(0, 85, 8), [1960, 1962, 1964, 1966, 1968, 1970, 1972, 1974, 1976, 1978, 1980])

fig.autofmt_xdate()
plt.tight_layout()

# Create the directory if it doesn't exist
if not os.path.exists('figures'):
    os.makedirs('figures')

plt.savefig('figures/CH01_F01_peixeiro.png', dpi=300)

"""時間序列的三個組成部分：趨勢、季節性成分和殘差

所有時間序列都可以分解為這三個要素

將時間序列的各個組成部分視覺化稱為分解。時間序列分析被定義為一種統計任務，它將時間序列分解成不同的組成部分。我們可以將每個組成部分視覺化，這有助於我們識別資料中的趨勢和季節性模式，而這些趨勢和模式並非總是能夠僅透過查看資料集就能直接發現的。


趨勢代表時間序列中緩慢的變化。它使序列隨時間推移逐漸增加或減少。

季節性成分代表序列中的季節性模式。這些週期會在固定的時間內反覆出現。

殘差代表了無法用趨勢和季節性成分解釋的行為。它們對應於隨機誤差，也稱為白噪音。

非平穩性、季節性效應以及外生變數的影響
"""

advanced_decomposition = STL(df.data, period=4).fit()
fig, (ax1, ax2, ax3, ax4) = plt.subplots(nrows=4, ncols=1, sharex=True)

ax1.plot(advanced_decomposition.observed)
ax1.set_ylabel('Observed')

ax2.plot(advanced_decomposition.trend)
ax2.set_ylabel('Trend')

ax3.plot(advanced_decomposition.seasonal)
ax3.set_ylabel('Seasonal')

ax4.plot(advanced_decomposition.resid)
ax4.set_ylabel('Residuals')


plt.xticks(np.arange(0, 85, 8), [1960, 1962, 1964, 1966, 1968, 1970, 1972, 1974, 1976, 1978, 1980])

fig.autofmt_xdate()
plt.tight_layout()

plt.savefig('figures/CH01_F02_peixeiro.png', dpi=300)

"""# Ch2

預測平均值

研究強生公司 1960 年至 1980 年以美元 （USD） 計算的季度每股收益。我們的目標是使用 1960 年至 1979 年底的數據來預測 1980 年的四個季度。
"""